Repository trompette/php-feature-toggles, pull requests merged in 2022-01, with the labels that each got.

#36 Add missing return type
  sources/Bundle/FeatureTogglesConfiguration.php
  sources/Bundle/FeatureTogglesExtension.php
  sources/Console/ConfigureFeatureCommand.php
  sources/Console/MigrateDBALSchemaCommand.php
  sources/Console/ShowFeatureConfigurationCommand.php
Labels: Improvement

#38 Leverage PHP 7.4
  sources/Bundle/FeatureTogglesExtension.php
  sources/Console/ConfigureFeatureCommand.php
  sources/Console/MigrateDBALSchemaCommand.php
  sources/Console/ShowFeatureConfigurationCommand.php
  sources/DBAL/SchemaMigrator.php
  sources/FeatureDefinition.php
  sources/FeatureRegistry.php
  sources/ORM/SchemaSubscriber.php
  sources/OnOffStrategy/OnOff.php
  sources/PercentageStrategy/Percentage.php
  sources/ToggleRouter.php
  sources/WhitelistStrategy/Whitelist.php
  tests/Bundle/FeatureTogglesBundleTest.php
  tests/Console/ConfigureFeatureCommandTest.php
  tests/Console/MigrateDBALSchemaCommandTest.php
  tests/Console/ShowFeatureConfigurationCommandTest.php
  tests/DBAL/ConfigurationRepositoryTest.php
  tests/DBAL/OnOffStrategyConfigurationRepositoryTest.php
  tests/DBAL/PercentageStrategyConfigurationRepositoryTest.php
  tests/DBAL/WhitelistStrategyConfigurationRepositoryTest.php
  tests/FeatureRegistryTest.php
  tests/ORM/SchemaSubscriberTest.php
  tests/OnOffStrategy/OnOffTest.php
  tests/PercentageStrategy/PercentageTest.php
  tests/ToggleRouterTest.php
  tests/WhitelistStrategy/WhitelistTest.php
Labels: Improvement

#39 Make FeatureRegistry more explicit
  sources/Bundle/FeatureTogglesExtension.php
  sources/FeatureRegistry.php
  tests/Bundle/FeatureTogglesBundleTest.php
  tests/FeatureRegistryTest.php
Labels: Improvement

#40 Install and configure PHPStan
  .github/workflows/static-analysis.yml
  composer.json
  sources/Bundle/FeatureTogglesExtension.php
  sources/Console/ConfigureFeatureCommand.php
  sources/Console/MigrateDBALSchemaCommand.php
  sources/Console/ShowFeatureConfigurationCommand.php
  sources/DBAL/PercentageStrategyConfigurationRepository.php
  sources/DBAL/WhitelistStrategyConfigurationRepository.php
  sources/FeatureRegistry.php
  sources/ORM/SchemaSubscriber.php
  sources/ToggleRouter.php
  sources/TogglingStrategy.php
  sources/WhitelistStrategy/ConfigurationRepository.php
  tests/DBAL/ConfigurationRepositoryTest.php
  tests/DBAL/OnOffStrategyConfigurationRepositoryTest.php
  tests/DBAL/PercentageStrategyConfigurationRepositoryTest.php
  tests/DBAL/WhitelistStrategyConfigurationRepositoryTest.php
  tests/ToggleRouterTest.php
  tests/WhitelistStrategy/WhitelistTest.php
Labels: Improvement, Tooling

#42 Simplify FeatureRegistry
  sources/Bundle/FeatureTogglesExtension.php
  sources/FeatureRegistry.php
  tests/Bundle/FeatureTogglesBundleTest.php
  tests/FeatureRegistryTest.php
Labels: Improvement, BC break

#41 Update vendors constraints
  .github/workflows/automated-tests.yml
  composer.json
Labels: Improvement, BC break

#43 Add ToggleRouterInterface
  sources/Console/ConfigureFeatureCommand.php
  sources/Console/ShowFeatureConfigurationCommand.php
  sources/ToggleRouter.php
  sources/ToggleRouterInterface.php
  tests/Console/ConfigureFeatureCommandTest.php
  tests/Console/ShowFeatureConfigurationCommandTest.php
Labels: Improvement

#44 Mark all classes final
  sources/Bundle/FeatureTogglesBundle.php
  sources/Bundle/FeatureTogglesConfiguration.php
  sources/Bundle/FeatureTogglesExtension.php
  sources/Console/ConfigureFeatureCommand.php
  sources/Console/MigrateDBALSchemaCommand.php
  sources/Console/ShowFeatureConfigurationCommand.php
  sources/DBAL/OnOffStrategyConfigurationRepository.php
  sources/DBAL/PercentageStrategyConfigurationRepository.php
  sources/DBAL/WhitelistStrategyConfigurationRepository.php
  sources/FeatureDefinition.php
  sources/FeatureRegistry.php
  sources/ORM/SchemaSubscriber.php
  sources/OnOffStrategy/OnOff.php
  sources/PercentageStrategy/Percentage.php
  sources/ToggleRouter.php
  sources/WhitelistStrategy/Whitelist.php
Labels: Improvement, BC break

#45 Add alias for ToggleRouterInterface in container
  README.md
  sources/Bundle/FeatureTogglesExtension.php
  tests/Bundle/FeatureTogglesBundleTest.php
Labels: Improvement
